language: ruby

rvm:
- 2.4.1

services:
  - postgresql

before_script:
  - psql -c 'create database platform_test;' -U postgres

test:
  adapter: postgresql
  database: platform_test

addons:
  postgresql: "9.6"
